#!/bin/sh
# Renders the Homebrew formula that release.yml's mirror job publishes to
# Fendix-app/homebrew-fendix. It is the only source of that formula:
# Formula/fendix.rb in this repo is this script's output for the current
# stable release, and scripts/release/test-homebrew-formula.sh fails if the
# two drift apart.
#
# Usage:
#   render-homebrew-formula.sh <tag> <darwin-arm64-sha256> <darwin-amd64-sha256> \
#     <linux-arm64-sha256> <linux-amd64-sha256>
#
# Homebrew takes the version from the URL's /releases/download/vX.Y.Z/ path,
# so it always follows the tag. Older Homebrew misread these URLs as "64"
# (from `...-amd64` / `...-arm64`) and recorded installs under that version;
# current Homebrew reads the tag but then ranks the installed "64" above any
# 3.x release, so those installs were never offered an upgrade.
# version_scheme 1 ranks every release above them. Do not add an explicit
# `version`: `brew audit --strict` (the tap's CI) rejects it as redundant
# with the URL. Never lower version_scheme.
#
# FENDIX_FORMULA_BASE_URL replaces the release download base. It exists for
# the Homebrew upgrade test, which serves locally built binaries; releases
# never set it.
set -eu

fail() {
    echo "render-homebrew-formula: $1" >&2
    exit 2
}

[ "$#" -eq 5 ] || fail "usage: $0 <tag> <darwin-arm64> <darwin-amd64> <linux-arm64> <linux-amd64> (SHA-256 values)"

TAG=$1
# Stable tags only: the mirror job skips prereleases, and Homebrew would
# order 3.5.1-rc.1 above 3.5.1.
printf '%s' "$TAG" | grep -Eqx 'v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)' ||
    fail "tag must be a stable release tag such as v3.5.1, not '$TAG'"
for sha in "$2" "$3" "$4" "$5"; do
    printf '%s' "$sha" | grep -Eqx '[0-9a-f]{64}' ||
        fail "'$sha' is not a lowercase SHA-256"
done

BASE=${FENDIX_FORMULA_BASE_URL:-https://github.com/Fendix-app/Fendix/releases/download}

cat <<EOF
# Homebrew formula for Fendix — hybrid API and code security scanner.
#
# Tap and install:
#   brew tap Fendix-app/fendix
#   brew install fendix
#
# This file is auto-regenerated by the engine repo's release.yml on
# every \`v*\` tag. Hand-edits here will be overwritten on the next
# release; edit the canonical copy in the engine repo instead.

class Fendix < Formula
  desc "Application security scanner with evidence-backed release decisions"
  homepage "https://fendix.dev"
  license "MIT"
  version_scheme 1

  depends_on "python@3.11" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/${TAG}/fendix-${TAG}-darwin-arm64"
      sha256 "$2"
    else
      url "${BASE}/${TAG}/fendix-${TAG}-darwin-amd64"
      sha256 "$3"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE}/${TAG}/fendix-${TAG}-linux-arm64"
      sha256 "$4"
    else
      url "${BASE}/${TAG}/fendix-${TAG}-linux-amd64"
      sha256 "$5"
    end
  end

  def install
    bin.install Dir["fendix-*"].first => "fendix"
  end

  def caveats
    <<~EOC
      This formula installs the standalone Go binary and recommends a Python
      interpreter, but it does not install the Fendix Python analyzer tree.
      --code auto-enables that phase; without a version-matched tree through
      FENDIX_ENGINE or an engine pin, the phase is recorded as skipped while
      native analyzers continue. Use the official container or a source
      checkout for ready-to-run hybrid coverage.

      Quick start:
        fendix scan --url https://api.example.com
        fendix scan --code ./src --python-engine=false --format html -o report.html
    EOC
  end

  test do
    assert_match "fendix version", shell_output("#{bin}/fendix version")
  end
end
EOF
