package i18n

// English returns the English Strings. This is the source language —
// every other constructor mirrors its field set; the audit test
// `TestStrings_EveryFieldTranslatedInEveryLanguage` ensures no field is
// accidentally empty.
func English() Strings {
	return Strings{
		ReportTitle:       "Fendix Security Report",
		ScanSubtitle:      "{target} — {mode} scan — {duration}",
		GeneratedByFendix: "Generated by Fendix",

		SeverityCritical: "Critical",
		SeverityHigh:     "High",
		SeverityMedium:   "Medium",
		SeverityLow:      "Low",
		SeverityInfo:     "Info",

		ConfidenceHigh:   "High",
		ConfidenceMedium: "Medium",
		ConfidenceLow:    "Low",

		SectionSummary:     "Summary",
		SectionFindings:    "Findings",
		SectionRemediation: "Remediation",
		SectionEvidence:    "Evidence",
		SectionReferences:  "References",
		SectionMetadata:    "Scan Metadata",
		ColumnID:           "ID",
		ColumnTitle:        "Title",
		ColumnSeverity:     "Severity",
		ColumnLocation:     "Location",
		ColumnFix:          "Fix",

		SortByLabel:        "Sort by:",
		SortBySeverity:     "Severity",
		SortByEndpoint:     "Endpoint",
		SortBySource:       "Source",
		ExpandAll:          "Expand All",
		CollapseAll:        "Collapse All",
		FieldEvidence:      "Evidence",
		FieldFix:           "Fix",
		FieldSource:        "Source",
		FieldCategory:      "Category",
		FieldConfidence:    "Confidence",
		FieldAffected:      "Affected endpoints",
		FieldReachable:     "Reachable dataflow",
		FieldReferences:    "References",
		FieldLocation:      "Location",
		ConfidenceLabel:    "confidence",
		StatusBlocking:     "Blocking",
		StatusConfirmed:    "Confirmed",
		ScanStartedLabel:   "Scan started:",
		DurationLabel:      "Duration:",
		ModeLabel:          "Mode:",
		EndpointsLabel:     "Endpoints:",
		TotalFindingsLabel: "Total findings:",
		NoFindingsMessage:  "No findings to report.",

		CoverageTitle:                    "Scanner coverage",
		CoverageAnalyzer:                 "Analyzer",
		CoverageClass:                    "State",
		CoverageReason:                   "Reason",
		CoverageAttempts:                 "Attempts",
		CoverageDetail:                   "Detail",
		CoverageComplete:                 "coverage complete",
		CoverageIncomplete:               "coverage incomplete:",
		CoverageRequiredMissing:          "required analyzers not delivered:",
		CoverageNotRecorded:              "coverage not recorded by this engine version",
		CoverageNotMeasured:              "coverage not measured",
		VerdictPass:                      "Passed",
		VerdictWarn:                      "Warning",
		VerdictBlocked:                   "Blocked",
		VerdictBlockedCoverageIncomplete: "Blocked — coverage also incomplete",
		VerdictCoverageIncomplete:        "Coverage incomplete",
		ClassOK:                          "ran", ClassNotApplicable: "not applicable", ClassDisabled: "disabled", ClassUnavailable: "unavailable",
		ClassUnsupported: "unsupported", ClassFailed: "failed", ClassUnknown: "unknown",
	}
}
